services:
  poke_poke_mmdetection:
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '16gb'
    image: nvcr.io/nvidia/pytorch:22.10-py3
    environment:
      - CUDA_LAUNCH_BLOCKING=1
    # コンテナ名を明示的に指定する
    # container_name: nvidia_pytorch-container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/home/Pokemon-SV-Detection
      # - D:\PROJECT\201_HaMaruki\201_60_PokemonSV\Pokemon-SV-Datasets:/home/pokemon-sv-datasets
      # - D:\PROJECT\201_HaMaruki\201_60_PokemonSV\Pokemon-SV-Work_dirs:/home/pokemon-sv-work_dirs
      - D:\raw:/home/Ika-Datasets/raw
    working_dir: /home/Pokemon-SV-Detection/mmdetection

    ports:
      - "6161:6161"
    # command:
    #   jupyter-lab --ip 0.0.0.0 --allow-root -b localhost --port=6666
    #   # nvidia-smi
    
    tty:
      true